### ISSUE TITLE
DAVdroid does not sync, Undefined index: userid

### ISSUE THREAD

**Issue by WTRipper** [owncloudarchive/calendar#1044]
### Steps to reproduce
1. Use DAVdroid to sync your calendars from owncloud.
2. Edit a calendar in aCalendar.

### Expected behaviour
DAVdroid should upload the events.

### Actual behaviour
DAVdroid does not sync and gives an error message (see below).

### Server configuration
**Operating system**:
 Raspbian
**Web server:**
Apache 2.4.10
**Database:**

**PHP version:**
5.6.17
**ownCloud version:** (see ownCloud admin page)
8.2.3
**Updated from an older ownCloud or fresh install:**
Update from 8.2.2
**Where did you install ownCloud from:**
http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_8.0/
**Signing status (ownCloud 9.0 and above):**

**List of activated apps:**

Activity 2.1.4
Deleted files 0.7.0
External storage support 0.3.0
First Run Wizard 1.1
Gallery 14.2.0
Mail Template Editor 0.1
PDF Viewer 0.7
Provisioning API 0.3.0
Share Files 0.7.0
Text Editor 2.0
Updater 0.6
Versions 1.1.0
Video Viewer 0.1.3
Calendar 0.8.2
Contacts 0.5.0.0
Documents 0.11.1
Tasks 0.8.1
ocDownloader 1.5
OwnNote 1.07

**The content of config/config.php:**
```
{
 "system": {
        "instanceid": "ocmrjdled4dp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXXXXXXX.ddns.net",
            "192.168.2.148"
        ],
        "datadirectory": "\/media\/usb-hdd\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/XXXXXXXXX.ddns.net\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.3.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\APC",
        "filesystem_check_changes": 1,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice"
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
DAVdroid

**Operating system:**
Android 6.0.1 (MMB29Q)
### DAVdroid debug information (error message)
```
SYNCHRONIZATION INFO

Synchronization phase: 4

Account name: joniwolli@gmx.de

Authority: com.android.calendar

 

HTTP REQUEST:

PUT https://***MYDOMAIN***.ddns.net/remote.php/caldav/calendars/***my_user_name***/contact_birthdays/5af99b92-e923-41f2-aa48-704f241feaf7.ics

Content-Length: 325

Content-Type: text/calendar;charset=utf-8

If-None-Match: *

 

BEGIN:VCALENDAR[CR][LF]

VERSION:2.0[CR][LF]

PRODID:+//IDN bitfire.at//DAVdroid/0.9.1.3 ical4android ical4j/2.x[CR][LF]

BEGIN:VEVENT[CR][LF]

DTSTAMP:20160322T212100Z[CR][LF]

UID:5af99b92-e923-41f2-aa48-704f241feaf7[CR][LF]

DTSTART;VALUE=DATE:20160415[CR][LF]

DTEND;VALUE=DATE:20160416[CR][LF]

SUMMARY:Erster Praktikumstag[CR][LF]

LOCATION:***LOCATION***[CR][LF]

STATUS:CONFIRMED[CR][LF]

END:VEVENT[CR][LF]

END:VCALENDAR[CR][LF]

 

 

HTTP RESPONSE:

http/1.1 403 Forbidden

Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0

Connection: Keep-Alive

Content-Length: 305

Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *

Content-Type: application/xml; charset=utf-8

Date: Tue, 22 Mar 2016 21:21:03 GMT

Expires: Thu, 19 Nov 1981 08:52:00 GMT

Keep-Alive: timeout=5, max=99

OkHttp-Received-Millis: 1458681661514

OkHttp-Sent-Millis: 1458681660964

Pragma: no-cache

Server: Apache/2.4.10 (Raspbian)

Strict-Transport-Security: max-age=15768000; includeSubDomains; preload

X-Content-Type-Options: nosniff

X-Frame-Options: SAMEORIGIN

X-Robots-Tag: none

X-Sabre-Version: 2.1.9

X-XSS-Protection: 1; mode=block

 

<?xml version="1.0" encoding="utf-8"?>[LF]

<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">[LF]

  <s:sabredav-version>2.1.9</s:sabredav-version>[LF]

  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>[LF]

  <s:message>You do not have the permissions to add events to this calendar.</s:message>[LF]

</d:error>[LF]

 

 

STACK TRACE:

at.bitfire.dav4android.exception.HttpException: 403 Forbidden

at.bitfire.dav4android.exception.HttpException: 403 Forbidden

at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:281)

at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:286)

at at.bitfire.dav4android.DavResource.put(DavResource.java:181)

at at.bitfire.davdroid.syncadapter.SyncManager.uploadDirty(SyncManager.java:335)

at at.bitfire.davdroid.syncadapter.SyncManager.performSync(SyncManager.java:159)

at at.bitfire.davdroid.syncadapter.CalendarsSyncAdapterService$SyncAdapter.onPerformSync(CalendarsSyncAdapterService.java:58)

at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)

 

SOFTWARE INFORMATION

DAVdroid version: 0.9.1.3 (87) Sat Jan 02 11:24:54 GMT+01:00 2016

Installed from: com.android.vending

JB Workaround installed: no

 

CONFIGURATION

System-wide synchronization: automatically

Account: ***mymail***@gmx.de

  Address book sync. interval: 1440 min

  Calendar     sync. interval: 1440 min

  OpenTasks    sync. interval: 1440 min

 

SYSTEM INFORMATION

Android version: 6.0.1 (MMB29Q)

Device: LGE Nexus 5 (hammerhead)
```
#### Web server error log
```
I see nothing relevant
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"Y09f2Bjrkv7\/1N7JFPzR","remoteAddr":"217.XXX.XX.XX","app":"PHP","message":"Undefined index: userid at \/var\/www\/owncloud\/apps\/calendar\/lib\/object.php#159","level":3,"time":"2016-03-23T08:20:59+00:00"}

{"reqId":"6e29OC0c0lTqbeOgy4Wn","remoteAddr":"217.XXX.XX.XX","app":"PHP","message":"Undefined index: userid at \/var\/www\/owncloud\/apps\/calendar\/lib\/object.php#159","level":3,"time":"2016-03-23T08:45:31+00:00"}

{"reqId":"sK1sJ7U7v+JGvVH+MRZy","remoteAddr":"217.XXX.XX.XX","app":"PHP","message":"Undefined index: userid at \/var\/www\/owncloud\/apps\/calendar\/lib\/object.php#159","level":3,"time":"2016-03-23T08:45:58+00:00"}

```

**Comment by gvde** [comment]
> PUT https://***MYDOMAIN***.ddns.net/remote.php/caldav/calendars/***my_user_name***/contact_birthdays/5af99b92-e923-41f2-aa48-704f241feaf7.ics

The birthday calendar is automatically generated from your contacts. You cannot edit anything in that calendar. It's read only. To make changes you have to change the contact.

**Comment by WTRipper** [comment]
Ah thx! Wow that it's a simple answer :D
